execute pathogen#infect()
runtime! plugin/sensible.vim

syntax on
filetype plugin indent on

set tabstop=2
set shiftwidth=2
set expandtab

" Allow buffers to be changed without saving first.
set hidden

set mouse=a
set number
highlight clear SignColumn

let mapleader=","
map <Leader>p :CtrlPMixed<CR>
